// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqNnwIrZz6_6m3rUQhPJf6m91Gu02TNH4',
    appId: '1:1057944947099:web:64652671632640a18ab93e',
    messagingSenderId: '1057944947099',
    projectId: 'nft-proj-929dc',
    authDomain: 'nft-proj-929dc.firebaseapp.com',
    storageBucket: 'nft-proj-929dc.appspot.com',
    measurementId: 'G-2Y26E24C16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVTI3ACQpL6iTdBNtw2fWAP_n6jlF4-k',
    appId: '1:1057944947099:android:e850e001c4efaca68ab93e',
    messagingSenderId: '1057944947099',
    projectId: 'nft-proj-929dc',
    storageBucket: 'nft-proj-929dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD11j4Sd728uXLYeCPP8wb0MnPLLc7j3-8',
    appId: '1:1057944947099:ios:aea29a31ee73933a8ab93e',
    messagingSenderId: '1057944947099',
    projectId: 'nft-proj-929dc',
    storageBucket: 'nft-proj-929dc.appspot.com',
    iosClientId: '1057944947099-72l9om2a8f75nrmmiokj35kllis5ki19.apps.googleusercontent.com',
    iosBundleId: 'com.o3shx.nftproj',
  );
}
